<?php
/**
 * Created by PhpStorm.
 * User: Ben
 * Date: 5/1/2016
 * Time: 7:50 PM
 */

/**
 * @param $data
 *
 * @return array
 */
function form_tracking_statistics_form_tracking_session_data($data) {
  $new_data = [
    'path' => form_tracking_statistics_get_visitor_path($data['session_id'], $data['timestamp']),
  ];

  return $new_data;
}

/**
 * @param $session_id
 * @param bool $current_timestamp A timestamp, or true to use time() or false
 *                                to not diff the last step in the path
 *
 * @return array
 */
function form_tracking_statistics_get_visitor_path($session_id, $current_timestamp = FALSE) {
  $path = [];

  $results = db_query('SELECT * FROM {accesslog} WHERE sid = :sid', [':sid' => $session_id]);

  foreach ($results as $record) {
    $path[] = [
      'timestamp' => $record->timestamp,
      'time_on_page' => 0,
      'title' => form_tracking_statistics_get_title($record),
      'path' => $record->path,
      'referrer' => $record->url,
      'uid' => $record->uid,
    ];
  }

  form_tracking_statistics_calculate_time_on_page($path, $current_timestamp);

  return $path;
}

/**
 * @param $path
 * @param bool $current_timestamp
 *
 * @return mixed
 */
function form_tracking_statistics_calculate_time_on_page(&$path, $current_timestamp = FALSE) {
  foreach ($path as $index => $item) {
    if (isset($path[$index + 1])) {
      $path[$index]['time_on_page'] = $path[$index + 1]['timestamp'] - $item['timestamp'];
    } elseif ($current_timestamp) {
      if (!is_numeric($current_timestamp)) {
        $current_timestamp = time();
      }

      $path[$index]['time_on_page'] = $current_timestamp - $item['timestamp'];
    }
  }

  return $path;
}

/**
 * @param $record
 *
 * @return null|string
 */
function form_tracking_statistics_get_title($record) {
  if (!empty($record->title)) {
    return $record->title;
  }

  $front_path = drupal_get_normal_path(variable_get('site_frontpage', 'node'));

  $title = ($record->path == $front_path) ? '[front page]' : '[no title]';

  return t($title);
}
